version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Devops/Dockerfile-python
    volumes:
      - .:/app
    user: 1000:1000
    ports:
      - 8000:8000
    depends_on:
      - database
    env_file:
      - .env
    environment:
      DEV: yesyes
      HOME: /app/Devops/home
    command: python rundev.py

  database:
    image: postgres:12-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env


volumes:
  db-data:
