# Generated by Django 3.0.7 on 2020-07-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
