# Generated by Django 3.0.7 on 2020-07-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_question_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='questions',
            field=models.ManyToManyField(related_name='_template_questions_+', to='interview.Question'),
        ),
    ]
