# Generated by Django 3.0.7 on 2020-07-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_template_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='comments',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
