# Generated by Django 3.0.7 on 2020-08-17 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200816_2208'),
        ('interview', '0005_auto_20200730_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='band',
        ),
        migrations.AddField(
            model_name='question',
            name='seniority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='base.Seniority'),
            preserve_default=False,
        ),
    ]
