# Generated by Django 3.0.7 on 2020-08-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_auto_20200816_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewer_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
