# Generated by Django 3.0.7 on 2020-07-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='base.Band'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subareas', to='base.Area'),
        ),
    ]
