# Generated by Django 3.0.7 on 2020-08-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200722_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seniority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seniority', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='position',
            name='band',
        ),
    ]
